---
title: "Learn Analytics"
author: "Thamizhiniyan Pugazhenthi"
date: "17/11/2021"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir= normalizePath('..'))
knitr::opts_chunk$set(fig.width=12, fig.height=8)
```

```{r ProjectTemplate, include = FALSE}
library(ProjectTemplate)
load.project()
```

```{r plots, echo = FALSE}
#various analysis of data

# Basic bar plot

#Analysis by age

ggplot(enrolment, aes(age_range)) + geom_bar(stat="count") + 
  
  geom_text(stat='count', aes(label=..count..), vjust=-1) + ggtitle("Count of enrolment by age") + theme_minimal()

#Analysis by gender

ggplot(enrolment, aes(gender)) + geom_bar(stat="count") + 
  
  geom_text(stat='count', aes(label=..count..), vjust=-1) + ggtitle("Count of enrolment by gender") + theme_minimal()

#Analysis by highest education

ggplot(enrolment, aes(highest_education_level)) + geom_bar(stat="count") + 
  
  geom_text(stat='count', aes(label=..count..), vjust=-1) + ggtitle("Count of enrolment by highest education level") + 
  theme_minimal()

#Analysis by employment status

ggplot(enrolment, aes(employment_status)) + geom_bar(stat="count") + 
  
  geom_text(stat='count', aes(label=..count..), vjust=-1) + ggtitle("Count of enrolment by employment status") + 
  
  theme_minimal()

#Analysis by question response

questionresponse %>%
  
  filter(quiz_question != "") %>% unique(.) %>%

  ggplot(aes(correct)) + geom_bar(stat="count") +
  
  geom_text(stat='count', aes(label=..count..), position = position_stack(vjust=0.5)) + ggtitle("Learners by 
                                                                                                
                                                                                                responses") + theme_minimal()

questionresponse %>%
  
  filter(quiz_question != "") %>% unique(.) %>%
  
  ggplot(aes(fill = correct, x = quiz_question)) + geom_bar(position = "stack", stat="count") +
  
  geom_text(stat='count', aes(label=..count..), position = position_stack(vjust=0.5)) + ggtitle("Learners for each 
                                                                                                
                                                                                                question by responses") + theme_minimal()


#Analysis by leaving survey

leavingsurvey %>%
  
  filter(last_completed_step != "NA") %>%
  
  ggplot(aes(last_completed_step)) + geom_bar(stat="count") +
  
  geom_text(stat='count', aes(label=..count..), position = position_stack(vjust=0.5)) + 
  
  ggtitle("Leaving response by step number") + theme_minimal()



#Analysis by each run

enrolcompile %>%
  
  ggplot(aes(x = run, y = count)) + geom_line() + geom_point() +
  
  geom_label(aes(label = count)) + ggtitle("Number of enrolments in each run") + theme_minimal()
  


quizruntruecompile %>%
  
  ggplot(aes(x = run, y = count, group = week, color = as.factor(week))) + geom_line() + geom_point() +
  
  scale_color_manual(values=c('#FF0000','#0000FF', '#097969')) + 
  
  geom_label(aes(label = count)) + labs(color = "week") +

  ggtitle("Number of correct responses to quiz by week in each run") + theme_minimal()


quizrunfalsecompile %>%
  
  ggplot(aes(x = run, y = count, group = week, color = as.factor(week))) + geom_line() + geom_point() +
  
  scale_color_manual(values=c('#FF0000','#0000FF', '#097969')) + 
  
  geom_label(aes(label = count)) + labs(color = "week") +
  
  ggtitle("Number of wrong responses to quiz by week in each run") + theme_minimal()


#leaving survey

leavingruncompile %>%
  
  ggplot(aes(x = run, y = count)) + geom_line() + geom_point() +
  
  geom_label(aes(label = count)) + geom_label(aes(label = count)) +
  
  ggtitle("Number of leaving survey by run") + theme_minimal()


```